---
- name: Print facts
  hosts: all
  become: yes
  #gather_facts: False
  tasks:
    - name: Print OS name
      debug:
        var: ansible_distribution
    - name: Print memory details
      debug:
        var: ansible_memory_mb.nocache
    - name: Print mount details
      debug:
        var: ansible_mounts[0]


