---
- name: Understandin vars
  hosts: all
  become: yes
  vars:
    USRNM: playuser
    COMM: variable from playbook
  tasks:
    - name: create user
      ansible.builtin.user:
        name: "{{USRNM}}"
        comment: "{{COMM}}"
      register: log
    - debug:
        var: log.name
    - debug:
        var: log.comment

